language: bash

os:
  - linux

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh; fi
  - bash miniconda3.sh -b -p $HOME/miniconda3
  - source "$HOME/miniconda3/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda init bash
  - source /home/travis/.bashrc

script:
  - travis_wait 30 bash create-conda-virtual-environment.sh
  - conda activate $CWD/env && echo $CONDA_DEFAULT_ENV
