language: ruby

os:
  - linux

services:
  - docker

before_install:
  - docker build -f Dockerfile --tag=sc4da:2.0.0 SC4DA
  #- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  #- docker run -it sc4da:2.0.0 bash
  #- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
  - echo 123
  #- bundle exec rake test
  #- bash test.sh
  #- Rscript test.r
  #- python test.py