language: bash

os:
  - linux

services:
  - docker

install:
  - travis_wait 45 docker build -f Dockerfile --tag=sc4da:2.0.0 .
  - docker ps -a

script:
  - docker run sc4da:2.0.0 bash test.sh
  - docker run sc4da:2.0.0 Rscript test.r
  - docker run sc4da:2.0.0 python test.py
