###############################################################################
#
#   Main software to be installed in the data analytic environment
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 07-10-2019
#   LICENSE: GPL
#
###############################################################################
---

channels:
  - conda-forge
  - bioconda
  - r
  - anaconda

dependencies:

  # Others:
  - make
  - cmake
  - git
  - cookiecutter
  - vim
  - perl
  - imagemagick
  - bedtools
  - samtools
  - sqlite
  - snakemake
  - jupyterlab

  # Python:
  - python
  - ipython
  - sphinx
  - tqdm
  - pyyaml
  - pytest
  - pylint
  - black
  - jinja2
  - biopython
  - rpy2
  - pybedtools
  - pysam
  - numpy
  - scipy
  - statsmodels
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - bokeh
  - scikit-learn
  - blas
  - libblas
  - mkl
  - mkl-service
  - theano
  - pymc3

  # R:
  - r-base
  - r-essentials
  - r-optparse
  - r-assertthat
  - r-rcolorbrewer
  - r-rcpp
  - r-numderiv
  - r-maxlik
  - r-statmod
  - r-gplots
  - r-tidyverse
  - r-tsibble
  - r-future
  - r-furrr
  - r-cowplot

...