###############################################################################
#
#   Main software to be installed in the data analytic environment
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 07-10-2019
#   LICENSE: Apache_2.0
#
###############################################################################
---

name: sc4da

channels:
  - conda-forge
  - bioconda
  - r
  - anaconda

dependencies:

  # Others:
  - make=4.2.1
  - bash=5.0.011 ######
  - cmake=3.15.4
  - git=2.23.0
  - cookiecutter=1.6.0
  - vim=8.1.1343
  - perl=5.26.2
  #- imagemagick
  #- bedtools
  #- samtools
  - sqlite=3.30.1
  - snakemake=5.7.0
  - nextflow=20.01.0 #######
  - nf-core=1.9 ######
  - graphviz=2.40.1 ######
  - jupyterlab=1.1.4
  - beakerx=1.4.1 #######
  - singularity=2.6.0

  # Python:
  - python=3.7.3
  - ipython=7.8.0
  - sphinx=2.2.0
  - tqdm=4.36.1
  - pyyaml=5.1.2
  - pytest=5.2.1
  - pylint=2.4.2
  - black=19.3b0
  - jinja2=2.10.3
  - biopython=1.74
  #- rpy2
  #- pybedtools
  #- pysam
  - numpy=1.17.2
  - scipy=1.3.1
  - statsmodels=0.10.1
  - pandas=0.25.1
  - matplotlib=3.1.1
  - seaborn=0.9.0
  - plotly=4.1.1
  - bokeh=1.3.4
  - scikit-learn=0.21.3
  #- blas
  #- libblas
  #- mkl
  #- mkl-service
  - theano=1.0.4
  - pymc3=3.7
  - tensorflow=1.13.1
  - keras=2.3.1
  - pytorch=1.4.0 #####

  # R:
  - r-base=3.6.1
  - r-essentials=3.6
  - r-optparse=1.6.4
  - r-maxlik=1.3_6
  - r-statmod=1.4.32
  - r-gplots=3.0.1.1
  - r-tidymodels=0.1.0 ####
  - r-tsibble=0.8.4
  - r-future=1.14.0
  - r-furrr=0.1.0
  - r-cowplot=1.0.0
  - r-projecttemplate=0.9.0 #####
  - r-roxygen2=7.1.0 #####
  - r-devtools=2.3.0 ######
  - r-usethis=1.6.0 #####
  - rstudio=1.1.456 #####

...
