###############################################################################
#
#   Main software to be installed in the data analytic environment
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 07-10-2019
#   LICENSE: GPL
#
###############################################################################
---

channels:
  - conda-forge
  - bioconda
  - r
  - krinsman

dependencies:

  # Others:
  - gcc_linux-64
  - gxx_linux-64
  - gfortran_linux-64
  - perl
  - imagemagick
  - make
  - cmake
  - git
  - cookiecutter
  - bedtools
  - samtools
  - vim

  # Python:
  - python
  - ipython
  - sqlite
  - pandas
  - scipy
  - statsmodels
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - bokeh
  - biopython
  - jupyterlab
  - jinja2
  - snakemake
  - scikit-learn
  - theano
  - pymc3
  - pytest
  - pylint
  - sphinx
  - pyyaml
  - pybedtools
  - pysam
  - tqdm

  # R:
  - r-base
  - r-essentials
  - rpy2
  - r-rcpp
  - r-tidyverse
  - r-numderiv
  - r-rcolorbrewer
  - r-statmod
  - r-maxlik
  - r-optparse
  - r-gplots
  - r-assertthat
  - r-tsibble
  - r-future
  - r-furrr

...