###############################################################################
#
#   Main software to be installed in the conda environment
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 07-10-2019
#   LICENSE: Apache_2.0
#
###############################################################################
---

name: sc4da

channels:
  - conda-forge
  - bioconda
  - r
  - pytorch
  - anaconda

dependencies:

  # GENERAL
  - bash=5.0.011
  - beakerx=1.4.1
  - beautysh=6.0.1
  - black=19.10b0
  - cmake=3.17.0
  - cookiecutter=1.7.2
  - cpplint=1.4.4
  - git=2.26.0
  - graphviz=2.38.0
  - imagemagick=7.0.8_54
  - ipython=7.13.0
  - jupyterlab=2.1.1
  - libopenblas=0.3.9
  - make=4.3.0
  - mkl-service=2.3.0
  - nextflow=20.01.0
  - nf-core=1.9.0
  - nodejs=12.4.0
  - openssl=1.1.1g
  - perl=5.26.2
  - perl-digest-md5=2.55.0
  - pip=20.0.2
  - pylint=2.4.4
  - python=3.7.6
  - r-base=3.6.1
  - rstudio=1.1.456
  - shellcheck=0.7.1
  - singularity=3.5.3
  - snakemake=5.15.0
  - sphinx=3.0.3
  - sqlite=3.30.1
  - vim=8.2.0647

  # PYTHON PACKAGES
  - biopython=1.76.0
  - bokeh=2.0.1
  - jinja2=2.11.2
  - keras=2.3.1
  - matplotlib=3.1.1
  - matplotlib-venn=0.11.5
  - numpy=1.18.1
  - pandas=1.0.3
  - plotly=4.6.0
  - pymc3=3.8.0
  - pytest=5.4.1
  - pytorch=1.5.0
  - pyyaml=5.3.1
  - scikit-learn=0.22.2.post1
  - scipy=1.4.1
  - seaborn=0.10.1
  - simplegeneric=0.8.1
  - statsmodels=0.11.1
  - theano=1.0.4
  - tqdm=4.45.0

  # R PACKAGES
  - r-cowplot=1.0.0
  - r-devtools=2.3.0
  - r-essentials=3.6.0
  - r-furrr=0.1.0
  - r-future=1.17.0
  - r-gplots=3.0.3
  - r-lintr=2.0.1
  - r-maxlik=1.3_8
  - r-optparse=1.6.6
  - r-projecttemplate=0.9.0
  - r-roxygen2=7.1.0
  - r-statmod=1.4.34
  - r-styler=1.3.2
  - r-tidymodels=0.1.0
  - r-tsibble=0.8.6
  - r-usethis=1.6.0

  # PIP-INSTALLED
  - pip:
    - clang-format==9.0.0
    - tensorflow==2.0.0

...
